### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by oberstet** [isra17/autobahn-autoreconnect#1]
The file `autobahn_autoreconnect/__init__.py` contains large chunks of code copied verbatim from https://github.com/tavendo/AutobahnPython/blob/master/autobahn/asyncio/wamp.py#L72, but the copyright header from the Autobahn project is missing. Please add the copyright header or remove the code. Thanks.

**Comment by leameow** [comment]
Sorry I didn't catch the issue before. Fixed by 0938a62898ea328c0e5ac8815198dfa88c59eeec.
