### ISSUE TITLE
__init__() got an unexpected keyword arguments: debug and debug_wamp

### ISSUE THREAD

**Issue by webCoderLOL** [isra17/autobahn-autoreconnect#2]
Not sure if I got wrong version of modules. I need to delete the debug and debug_wamp keyword arguments

`self._transport_factory = WampWebSocketClientFactory(_create_app_session, url=self._url, serializers=self._serializers)`

in **init**.py of autobahn_autoreconnect module. 

My environment is python3.5, autobahn 0.14.1, txaio 2.5.1, autobahn-autoreconnect 0.0.2

Did anyone experience the same thing?

**Comment by leameow** [comment]
This project hasn't been maintained since last year. I see this fork https://github.com/Danconnolly/autobahn-autoreconnect/commit/8a9b5500c8a213f71351313af04c2596c3a17fb9 seems to fix the issue, which I'm willing to pull in if a PR is open.

**Comment by webCoderLOL** [comment]
yeah, that is one thing. I make it easier to just to 

`from autobahn.websocket.util import parse_url as parseWsUrl`

What I am referring is the debug and debug_wamp keywords. Any thoughts?

**Comment by webCoderLOL** [comment]
sorry. I missed that the diff deleted those two keys. 

Thanks

**Comment by leameow** [comment]
Fixed by https://github.com/isra17/autobahn-autoreconnect/pull/5
