### ISSUE TITLE
New Stable Release

### ISSUE THREAD

**Issue by webCoderLOL** [isra17/autobahn-autoreconnect#20]
Hi,

Currently, the stable PIP release is 0.1.0 but it doesn't include the fix of 

```
try:
    self._loop.add_signal_handler(signal.SIGTERM, self.stop)
except NotImplementedError:
    pass
```

Even this is a small fix, do we have a plan to release a new PIP package? Thanks

**Comment by leameow** [comment]
I just uploaded `0.1.1` with the latest revision!

**Comment by webCoderLOL** [comment]
Thank you so much. I tested and it worked great.
