### ISSUE TITLE
New Component Instance Is Created After Reconnect

### ISSUE THREAD

**Issue by webCoderLOL** [isra17/autobahn-autoreconnect#21]
Hi, 

Autobahn-autoreconnect is a great tool to converting your WAMP app into a smart and try active connect to WAMP router. It is really cool, thanks for all the work. 

Recently, I noticed one thing that when every time WAMP app tries to reconnect, it actually re-instantiate a new object without cleaning up the old object. I assume this is not what we want. Here is my snippet of code
____________________________________________________________________________________
```
import asyncio
from autobahn_autoreconnect import ApplicationRunner
from autobahn.asyncio.wamp import ApplicationSession

class Component(ApplicationSession):
    def __init__(self, config):
        super(Component, self).__init__(config)
        self.myState = 0
        async def printState():
            print("{} state {}".format(self, self.myState))
            await asyncio.sleep(5)

        asyncio.ensure_future(printState)

    def onDisconnect(self):
        # asyncio.get_event_loop().stop()
        self.myState = -1
        print("Connect drops, autoreconnect should kick in")

if __name__ == "__main__":
    runner = ApplicationRunner(
            u"wss://1.2.3.4:443/ws",
            u"realm1",
            debug_app=True
    )
    runner.run(Component)
```
____________________________________________________________________________________
You will need to have a WAMP router to connect to and disconnect the network to fall into the reconnect cycle. You will see two outputs printing myState = -1 and myState =0 when you successfully reconnect. 

Any advice?

**Comment by leameow** [comment]
`runner.run` takes a factory called each time it needs to connect. If you want to persist the state you can use something like:

```python
class ApplicationFactory:
  def __init__(self, component_cls):
    self.instance = None
    self.component_cls = component_cls
  def __call__(self, *args, **kwargs):
    if not self.instance:
      self.instance = self.component_cls(*args, **kwargs)
    return self.instance

runner.run(ApplicationFactory(Component))
```

Obviously this code is untested, tweak it as you see fit :)

**Comment by webCoderLOL** [comment]
That's a cool way to wrap a class call. Looks like i need to dig deep on my Python skill. Thanks :)
